version: "3.9"
services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud-conversion-tool-api
    restart: always
    volumes:
      - ".:/app"
      - "./videos:/app/videos"
    env_file:
      - .env.lab
    tty: true
  server:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - gateway
    links:
      - gateway
